#!/bin/bash

volume=$(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1)
STEP_SIZE=${STEP_SIZE:-5}


case $BLOCK_BUTTON in
	3) i3-msg exec "termite -e alsamixer" > /dev/null ;;
  1) pactl set-sink-mute 0 toggle ;; # right click
  4) volume down 2> /dev/null ;; # scroll up
  5) volume up 2>/dev/null ;; # scroll down, decrease
esac

amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null && echo " $volume%" && exit

if [[ $volume -lt 50 ]]; then
	echo " $volume%"
else
	echo " $volume%"
fi


