#!/bin/bash

# echo $(iw dev wlp3s0 link 2>/dev/null | grep SSID | cut -d ":" -f2 | xargs) ($(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'))

if [[ $button == 1 ]]; then
	qs -s wifi-connect-network
fi

ip_address="$(hostname --ip-address | cut -d ' ' -f1)"

[[ -d /sys/class/net/enp0s20u1 ]] && echo "  $ip_address" && exit

[[ $(nmcli radio wifi) == disabled ]] && echo "" && exit

# echo " $(iw dev wlp3s0 link 2>/dev/null | grep SSID | cut -d ":" -f2 | xargs)" "($(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'))"


echo " $(iw dev wlp3s0 link 2>/dev/null | grep SSID | cut -d ":" -f2 | xargs)" "($ip_address)"

